apiVersion: v1
kind: Secret
metadata:
  name: om-admin-user
  namespace: mongodb
type: Opaque
stringData:
## TODO: set your desired Ops Manager admin user credentials here
  Password: "sc_admin_pwd1"
  Username: "admin"
  FirstName: "First"
  LastName: "Last"