apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: mongodb-user
  namespace: mongodb
spec:
  passwordSecretKeyRef:
  ## TODO: set the reference to the password secret you created
    name: mongodb-user-password
    key: password
  username: "admin"
  db: "admin"
  mongodbResourceRef:
    name: "demo"
  roles:
  - db: "admin"
    name: "root"