apiVersion: v1
kind: Secret
metadata:
  name: om-api-key-secret
  namespace: mongodb
stringData:
# TODO: In Ops Manager, generate an organization API key with Organization Owner role, put the credentials here
  publicKey: <public_key>
  privateKey: <private_key>