apiVersion: v1
kind: Secret
metadata:
  name: om-admin-user
  namespace: mongodb
type: Opaque
stringData:
## TODO: set your desired Ops Manager admin user credentials here
  Password: "<my-password>"
  Username: "<my-username>"
  FirstName: "<my-firstname>"
  LastName: "<my-lastname>"