---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  replicas: 1
  version: 8.0.16
  # TODO: set the reference to the secret you created for the admin user
  adminCredentials: <the secret you created earlier>
  externalConnectivity:
  # TODO: set your external connectivity option here
    type: <external connectivity option>
  applicationDatabase:
  # TODO: specify number of nodes in the replica set that will be used as the application database for Ops Manager
    members: <minimum number of nodes for a highly available replica set>
    version: 8.0.16
  
  # These settings can be configured in the Ops Manager UI after installation
  # but if we define them here we save some initial setup time.
  configuration:
    mms.ignoreInitialUiSetup: "true"
    mms.adminEmailAddr: admin@example.com
    mms.fromEmailAddr: admin@example.com
    mms.mail.hostname: mail.example.com
    mms.mail.port: "465"
    mms.mail.ssl: "true"
    mms.mail.transport: smtp
    mms.replyToEmailAddr: admin@example.com