apiVersion: v1
kind: Secret
metadata:
  name: demo-search-sync-source-password
  namespace: mongodb
type: Opaque
stringData:
## TODO: set your desired database user password here
  password: <my password>